### ISSUE TITLE
Missing option to assign ammo to Annihilator Beam

### ISSUE THREAD

**Issue by pkmnfrk** [SpaghettiToastBook/spaghettitoastbook.github.io#1]
Randovania has an option to make the Annihilator Beam give you ammo capacity, similar to the Light and Dark beams. However, the tracker doesn't have an option to configure this.

![image](https://user-images.githubusercontent.com/1333816/57662003-611aef00-75bb-11e9-91ca-e62c168ac9c1.png)

**Comment by SpaghettiToastBook** [comment]
Fixed by 005a084b1e22204e950b686315259e89ca6c1f33.
